from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name='index',),
    path("about/", views.about, name='about',),
    path("review/", views.review, name='review',),
    path("contact/", views.contact, name='contact',),
    path("chocolates/", views.chocolates, name='chocolates',),
    path("beverages/", views.beverages, name='beverages',),
    path("edible/", views.edible_items, name='edible',),
    path("dairyproduct/", views.dairyproduct, name='dairyproduct',),
    path("oil_ghee/", views.oil_ghee, name='oil_ghee',),
    path("personal_care/", views.personal_care, name='personal_care',),
    path("spices/", views.spices, name='spices',),
    path("staples/", views.staples, name='staples',),
    path("tea_coffee/", views.tea_coffee, name='tea_coffee',),
    path("fruits_vegetable/", views.fruits_vegetable, name='fruits_vegetable',),
    path("bakery_items/", views.bakery_items, name='bakery_items',),
    path("ready_to_eat/", views.ready_to_eat, name='ready_to_eat',),
    path("icecream_desert/", views.icecream_desert, name='icecream_desert',),
    path("snacks/", views.snacks, name='snacks',),
    path("fruit_nut/", views.fruit_nut, name='fruit_nut',),
    path("search/", views.search, name='search',),
    path("product_detail/<str:id>/", views.product_detail, name='product_detail',),
    path("product_detail2/<str:id>/", views.product_detail2, name='product_detail2',),
    path("product_detail3/<str:id>/", views.product_detail3, name='product_detail3',),
    path("product_detail4/<str:id>/", views.product_detail4, name='product_detail4',),
    path("product_detail5/<str:id>/", views.product_detail5, name='product_detail5',),
    path("product_detail6/<str:id>/", views.product_detail6, name='product_detail6',),
    path("product_detail7/<str:id>/", views.product_detail7, name='product_detail7',),
    path("product_detail8/<str:id>/", views.product_detail8, name='product_detail8',),
    path("product_detail9/<str:id>/", views.product_detail9, name='product_detail9',),
    path("product_detail10/<str:id>/", views.product_detail10, name='product_detail10',),
    path("product_detail11/<str:id>/", views.product_detail11, name='product_detail11',),
    path("product_detail12/<str:id>/", views.product_detail12, name='product_detail12',),
    path("product_detail13/<str:id>/", views.product_detail13, name='product_detail13',),
    path("product_detail14/<str:id>/", views.product_detail14, name='product_detail14',),
    path("checkout/", views.checkout, name='checkout',),

]