# Generated by Django 4.0.5 on 2022-07-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery_items_name', models.CharField(max_length=100)),
                ('bakery_items_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Edibleitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edibleitems_name', models.CharField(max_length=100)),
                ('edibleitems_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Fruit_nut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_nut_name', models.CharField(max_length=100)),
                ('fruit_nut_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Fruits_vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruits_vegetable_name', models.CharField(max_length=100)),
                ('fruits_vegetable_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Icecream_desert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icecream_desert_name', models.CharField(max_length=100)),
                ('icecream_desert_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Oil_ghee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_ghee_name', models.CharField(max_length=100)),
                ('oil_ghee_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_care_name', models.CharField(max_length=100)),
                ('personal_care_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ready_to_eat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_to_eat_name', models.CharField(max_length=100)),
                ('ready_to_eat_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snacks_name', models.CharField(max_length=100)),
                ('snacks_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Spices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spices_name', models.CharField(max_length=100)),
                ('spices_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Staples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staples_name', models.CharField(max_length=100)),
                ('staples_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tea_coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_coffee_name', models.CharField(max_length=100)),
                ('tea_coffee_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='chocolate',
            name='image',
            field=models.ImageField(blank=True, null=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='dairyproduct',
            name='image',
            field=models.ImageField(blank=True, null=0, upload_to=''),
        ),
    ]
