# Generated by Django 4.0.5 on 2022-07-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_bakery_items_edibleitems_fruit_nut_fruits_vegetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverages_name', models.CharField(max_length=100)),
                ('beverages_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=0, upload_to='')),
            ],
        ),
    ]
