# Generated by Django 4.0.5 on 2022-07-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
