# Generated by Django 4.0.5 on 2022-07-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0007_remove_review_comment_remove_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
